export const data = [
    {
      name: "Neha Mayumi",
      title: "Event Specialist",
      rating: 4.9,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["ui/ux", "accounting", "communication", "+5"],
      languages: ["English", "Arabic", "Hindi"],
      rate: 20,
      currency: "AED",
      match: 50,
      avatar: "https://github.com/shadcn.png",
    },
    {
      name: "Junaid Ali",
      title: "UI/UX Designer",
      rating: 4.7,
      outOf: 5,
      available: true,
      availabilityType: "Hybrid",
      skills: ["figma", "sketch", "accessibility"],
      languages: ["English", "Urdu"],
      rate: 35,
      currency: "USD",
      match: 70,
      avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    },
    {
      name: "Aisha Rahman",
      title: "Marketing Expert",
      rating: 4.5,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["seo", "ads", "copywriting", "+3"],
      languages: ["English", "French"],
      rate: 30,
      currency: "GBP",
      match: 82,
      avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    {
      name: "Carlos Mendes",
      title: "Financial Analyst",
      rating: 4.8,
      outOf: 5,
      available: false,
      availabilityType: "On-site",
      skills: ["finance", "excel", "data modeling"],
      languages: ["English", "Portuguese"],
      rate: 45,
      currency: "EUR",
      match: 64,
      avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
      name: "Emily Zhang",
      title: "Project Manager",
      rating: 4.9,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["agile", "scrum", "jira"],
      languages: ["English", "Mandarin"],
      rate: 50,
      currency: "USD",
      match: 88,
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
      name: "Ravi Kumar",
      title: "Software Engineer",
      rating: 4.6,
      outOf: 5,
      available: false,
      availabilityType: "Remote",
      skills: ["javascript", "react", "nodejs", "+2"],
      languages: ["English", "Hindi"],
      rate: 40,
      currency: "USD",
      match: 76,
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    {
      name: "Fatima Noor",
      title: "Content Writer",
      rating: 4.4,
      outOf: 5,
      available: true,
      availabilityType: "Hybrid",
      skills: ["blogging", "editing", "seo"],
      languages: ["English", "Arabic"],
      rate: 25,
      currency: "USD",
      match: 59,
      avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    },
    {
      name: "Leo Andersen",
      title: "DevOps Engineer",
      rating: 4.7,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["docker", "aws", "kubernetes", "+1"],
      languages: ["English", "Danish"],
      rate: 55,
      currency: "EUR",
      match: 92,
      avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    },
    {
      name: "Sophia Grace",
      title: "Graphic Designer",
      rating: 4.8,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["illustrator", "photoshop", "branding"],
      languages: ["English"],
      rate: 38,
      currency: "GBP",
      match: 74,
      avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    },
    {
      name: "Ahmed Youssef",
      title: "Full Stack Developer",
      rating: 4.9,
      outOf: 5,
      available: false,
      availabilityType: "On-site",
      skills: ["react", "nextjs", "express", "+4"],
      languages: ["English", "Arabic"],
      rate: 60,
      currency: "USD",
      match: 84,
      avatar: "https://randomuser.me/api/portraits/men/30.jpg",
    },
    {
      name: "Lina Torres",
      title: "HR Specialist",
      rating: 4.5,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["recruiting", "compliance", "onboarding"],
      languages: ["English", "Spanish"],
      rate: 28,
      currency: "USD",
      match: 63,
      avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    },
    {
      name: "Oscar Lee",
      title: "QA Engineer",
      rating: 4.6,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["testing", "cypress", "automation"],
      languages: ["English", "Korean"],
      rate: 33,
      currency: "USD",
      match: 71,
      avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    },
    {
      name: "Mia Bakshi",
      title: "Legal Consultant",
      rating: 4.3,
      outOf: 5,
      available: false,
      availabilityType: "Hybrid",
      skills: ["contracts", "compliance", "advice"],
      languages: ["English", "Hindi"],
      rate: 45,
      currency: "GBP",
      match: 67,
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    {
      name: "Nathan Brooks",
      title: "Copywriter",
      rating: 4.2,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["sales copy", "ads", "emails"],
      languages: ["English"],
      rate: 32,
      currency: "USD",
      match: 60,
      avatar: "https://randomuser.me/api/portraits/men/24.jpg",
    },
    {
      name: "Aya Chen",
      title: "Data Scientist",
      rating: 5.0,
      outOf: 5,
      available: true,
      availabilityType: "Remote",
      skills: ["python", "ml", "data analysis"],
      languages: ["English", "Mandarin"],
      rate: 75,
      currency: "USD",
      match: 96,
      avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    },
  ];